version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bank_rest_db
    environment:
      - POSTGRES_DB=bank-rest_db
      - POSTGRES_USER=hudoyor
      - POSTGRES_PASSWORD=root
    ports:
      - "5442:5432"
