spring.application.name=bankcards
spring.datasource.url=jdbc:postgresql://localhost:5442/bank-rest_db
spring.datasource.username=hudoyor
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase sozlamalari (bazani avtomat yaratish uchun)
spring.liquibase.change-log=classpath:db/migration/db.changelog-master.yaml
spring.liquibase.enabled=true

# JPA/Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.expiration=86400000
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE