spring.application.name=bankcards
spring.datasource.url=jdbc:postgresql://localhost:5442/bank-rest_db
spring.datasource.username=hudoyor
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8085

spring.liquibase.change-log=classpath:db/migration/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.expiration=86400000
app.encryption.key=1234567890123456
#spring.jpa.open-in-view=false
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE